c// Auth Types
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// Alert Types
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// Ingredient Types
export const GET_INGREDIENTS = 'GET_INGREDIENTS';
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT';
export const UPDATE_INGREDIENT = 'UPDATE_INGREDIENT';
export const INGREDIENT_ERROR = 'INGREDIENT_ERROR';
export const SET_CURRENT_INGREDIENT = 'SET_CURRENT_INGREDIENT';
export const CLEAR_CURRENT_INGREDIENT = 'CLEAR_CURRENT_INGREDIENT';
export const FILTER_INGREDIENTS = 'FILTER_INGREDIENTS';
export const CLEAR_FILTER = 'CLEAR_FILTER';
export const SCAN_BARCODE = 'SCAN_BARCODE';
export const OCR_PRICE_TAG = 'OCR_PRICE_TAG';
export const ENHANCED_OCR_SCAN = 'ENHANCED_OCR_SCAN';
export const OPTIMIZE_SCAN_PERFORMANCE = 'OPTIMIZE_SCAN_PERFORMANCE';

// Recipe Types
export const GET_RECIPES = 'GET_RECIPES';
export const ADD_RECIPE = 'ADD_RECIPE';
export const DELETE_RECIPE = 'DELETE_RECIPE';
export const UPDATE_RECIPE = 'UPDATE_RECIPE';
export const RECIPE_ERROR = 'RECIPE_ERROR';
export const SET_CURRENT_RECIPE = 'SET_CURRENT_RECIPE';
export const CLEAR_CURRENT_RECIPE = 'CLEAR_CURRENT_RECIPE';
export const CALCULATE_RECIPE_COST = 'CALCULATE_RECIPE_COST';

// Menu Types
export const GET_MENUS = 'GET_MENUS';
export const ADD_MENU = 'ADD_MENU';
export const DELETE_MENU = 'DELETE_MENU';
export const UPDATE_MENU = 'UPDATE_MENU';
export const MENU_ERROR = 'MENU_ERROR';
export const SET_CURRENT_MENU = 'SET_CURRENT_MENU';
export const CLEAR_CURRENT_MENU = 'CLEAR_CURRENT_MENU';
export const ANALYZE_MENU_PROFITABILITY = 'ANALYZE_MENU_PROFITABILITY';
export const OCR_MENU = 'OCR_MENU';
export const EXPORT_MENU_PDF = 'EXPORT_MENU_PDF';

// Purchase Types
export const GET_PURCHASES = 'GET_PURCHASES';
export const ADD_PURCHASE = 'ADD_PURCHASE';
export const DELETE_PURCHASE = 'DELETE_PURCHASE';
export const UPDATE_PURCHASE = 'UPDATE_PURCHASE';
export const PURCHASE_ERROR = 'PURCHASE_ERROR';
export const SET_CURRENT_PURCHASE = 'SET_CURRENT_PURCHASE';
export const CLEAR_CURRENT_PURCHASE = 'CLEAR_CURRENT_PURCHASE';
export const OCR_RECEIPT = 'OCR_RECEIPT';

// Analysis Types
export const CALCULATE_PROFIT_MARGINS = 'CALCULATE_PROFIT_MARGINS';
export const GENERATE_COST_BREAKDOWN = 'GENERATE_COST_BREAKDOWN';
export const SUGGEST_PRICING = 'SUGGEST_PRICING';
export const ANALYSIS_ERROR = 'ANALYSIS_ERROR';

// User Interface Types
export const SET_UI_PREFERENCE = 'SET_UI_PREFERENCE';
export const TOGGLE_BEGINNER_MODE = 'TOGGLE_BEGINNER_MODE';

// Integration Types
export const CONNECT_POS_SYSTEM = 'CONNECT_POS_SYSTEM';
export const SYNC_EXTERNAL_DATA = 'SYNC_EXTERNAL_DATA';
export const INTEGRATION_ERROR = 'INTEGRATION_ERROR';

// Offline/Sync Types
export const ENABLE_OFFLINE_MODE = 'ENABLE_OFFLINE_MODE';
export const SYNC_DATA = 'SYNC_DATA';
export const SYNC_ERROR = 'SYNC_ERROR';
export const SYNC_COMPLETE = 'SYNC_COMPLETE';

// International Cuisine Types
export const EXPAND_INGREDIENT_DATABASE = 'EXPAND_INGREDIENT_DATABASE';
export const ADD_INTERNATIONAL_CUISINE = 'ADD_INTERNATIONAL_CUISINE';

// Pricing Model Types
export const SET_PRICING_TIER = 'SET_PRICING_TIER';
export const UPDATE_FEATURE_ACCESS = 'UPDATE_FEATURE_ACCESS';